spring:
  application:
    name: policy-app

  datasource:
    url: jdbc:h2:mem:testdb
    username: anik
    password: anik
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true

server:
  port: 8080
